name: Update GitHub Readme Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  update-readme-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Top Languages Card
        uses: stats-organization/github-readme-stats-action@v2.0.1
        with:
          card: top-langs
          options: username=pljm0&layout=compact&theme=dracula
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile/top-langs.svg

          git diff --cached --quiet && exit 0

          git commit -m "Update GitHub Readme Stats"
          git push
